### ISSUE TITLE
"carotid artery endothelial cells" and "subclavian artery endothelial cell": use CL "endothelial cell of artery"?

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/epimap-metadata-harmonization#24]
No CL is available for "carotid artery endothelial cells" and "subclavian artery endothelial cell, but "endothelial cell of artery" is available
example ids: "IHECRE00003561.1", "IHECRE00003566.1"

**Comment by rnakato** [comment]
"carotid artery endothelial cells" and "subclavian artery endothelial cell" can be included in "endothelial cell of artery," but we think the position information is also important because atherosclerotic disease is often observed in the carotid artery. Is it possible to move the information "carotid artery" and "subclavian artery" to another column (e.g., "tissue_type")?
(Ryuichiro Nakato)

**Comment by rnakato** [comment]
I found "carotid artery endothelium" in UBERON.
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0019189

**Comment by SchulzLab** [comment]
all entries have been renamed as endothelial cell of artery and have updated the missing origin_sample if it was missing
